name: 'Test Observability Publish'
description: 'Publish test results to ably test observability'
author: 'Ably'
inputs:
  server-auth:
    description: 'auth key to publish to server'
    required: true
  server-url:
    description: 'url to the test observability website'
    required: false
    default: 'https://test-observability.herokuapp.com'
  path:
    description: 'path to .junit report files'
    required: false
    default: 'junit'
runs:
  using: 'node16'
  main: 'index.js'
