name: 'Test Observability Publish'
description: 'Publish test results to ably test observability'
author: 'Ably'
inputs:
  server-auth:
    description: 'auth key to publish to server'
    required: true
  server-url:
    description: 'url to the test observability website'
    required: false
    default: 'https://test-observability.herokuapp.com'
  path:
    description: 'path to .junit report files'
    required: false
    default: 'junit'
  github-token:
    description: 'a GitHub access token; if the repository is private then it must have `repo` scope'
    required: false
  job-name:
    description: 'the `name` property of the object corresponding to the current job in the response from the "list jobs for a workflow run attempt" GitHub API (https://docs.github.com/en/rest/actions/workflow-jobs?apiVersion=2022-11-28#list-jobs-for-a-workflow-run-attempt)'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
