on:
  pull_request:
  push:
    branches:
      - main

jobs:
  # An empty job, to allow us to demonstrate how to use job-name inside a
  # matrix job that has preceding jobs.
  first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Nothing to see here"

  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Arbitrary; just used so that we can execute inside a matrix job.
        some-value: [1, 2]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js version specified in .nvmrc
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install NPM packages
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Package
        run: npm run package

      - name: Test action
        uses: './'
        with:
          server-url: 'https://test-observability.herokuapp.com'
          server-auth: ${{ secrets.TEST_OBSERVABILITY_SERVER_AUTH_KEY }}
          path: 'junit'

      - name: Test action with job-name
        uses: './'
        with:
          server-url: 'https://test-observability.herokuapp.com'
          server-auth: ${{ secrets.TEST_OBSERVABILITY_SERVER_AUTH_KEY }}
          path: 'junit'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # We replicate the way in which GitHub assigns a name to a matrix job.
          job-name: check (${{ matrix.some-value }})
